#
# This is a comment.
#

This document is an example RFC which can be processed using the
"rfcdoc" toolset.  This section is the abstract, which is supposed to
give a simple overview of the intend of the document.

* Introduction

An introduction is a good thing, and I like good things.  So I have an
introduction.  You should too.

** Keywords

The keywords "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described in BCP
14, ^RFC2119^ ^RFC8174^ when, and only when, they appear in all capitals,
as shown here..

** Terminology

This document defines terms.  If your document does not, you might
need to import them.  All this should be described in this section.

* Some Content

Add your real content here.

*! start-appendix

* Example Appendix

If you need an appendix, consider putting it here.  If you don't need
an appendix, they can be removed via simple outpatient procedure.

{{document:
    name ;
    ipr trust200902;
    category std;
    references references.xml;
    title "Put Your Title Here";
    contributor "author:Your Name:Your Company:you@example.com";
}}
